pipeline:
  install:
    image: node:10.9.0
    commands:
      # - yarn install
      - pwd


  # testing:
  #   image: node:10.9.0
  #   group: testing
  #   commands:
  #     - yarn run test
  
  scp:
    image: appleboy/drone-scp
    pull: true
    host:
      - 139.162.9.68
    port: 22
    username: root
    password: xup6jo3fup6
    target: goodfood_admin
    source:
      - /drone/src/github.com/horsekitlin/goodfood_admin
    when:
      branch: develop
      # status: [ suucess ]
  # ssh:
  #   image: appleboy/drone-ssh
  #   host:
  #     - 139.162.9.68
  #   username: root
  #   password: password
  #   script:
  #     - echo ${ssh_key}
  #     - . /root/.nvm/nvm.sh && nvm use 10.9.0
  #     - mkdir /var/www/html/goodfood.tomaslin.com.tw
  #   when:
  #     branch: develop
