pipeline:
  # install:
  #   image: node:10.9.0
  #   commands:
  #     - node -v
  #     - npm -v
  #     - yarn --version
  #     - yarn install


  # testing:
  #   image: node:10.9.0
  #   group: testing
  #   commands:
  #     - yarn run test
  
  scp:
    image: appleboy/drone-scp
    pull: true
    host:
      - 139.162.9.68
    port: 22
    username: root
    target: /home/drone/demo
    source:
      - app.tar.gz
    when:
      branch: develop
      # status: [ suucess ]
  # ssh:
  #   image: appleboy/drone-ssh
  #   host:
  #     - 139.162.9.68
  #   username: root
  #   password: xup6jo3fup6
  #   script:
  #     - echo ${ssh_key}
  #     - . /root/.nvm/nvm.sh && nvm use 10.9.0
  #     - mkdir /var/www/html/goodfood.tomaslin.com.tw
  #   when:
  #     branch: develop
