language: node_js
node_js:
  - "10"
addons:
  ssh_known_hosts:
  - 139.162.9.68
before_install:
  - 'nvm install-latest-npm'
env:
  matrix:
  - REACT=16.4
sudo: false
script:
  - npm run test
after_success:
  - npm run coverage